import Head from 'next/head'
import { useState } from 'react'
import { Layout } from '../component/Layout/MainLayout'
import Nft from '../component/ViewNft'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
    <Nft />
      </Layout>
    </div>
  )
}
